### ISSUE TITLE
Uncaught (in promise) DOMException: Unable to decode audio data

### ISSUE THREAD

**Issue by kevinxbrown** [lorentzlasson/node-red-contrib-play-audio#1]
Hi, I liked the idea of the node, but I couldn't get it working when installed on Bluemix.

On Chrome, there was a message in the browser console: 
Uncaught (in promise) DOMException: Unable to decode audio data
Chrome Version 49.0.2623.110 (64-bit)
on Mac.

In firefox, an  alert message appeared.
Error: TypeError: invalid arguments

The flow I used in Node-RED was:

[{"id":"1df9a2f0.a8b265","type":"watson-text-to-speech","z":"4417bb2c.9f49e4","name":"Speech","lang":"english","voice":"en-US_MichaelVoice","format":"audio/ogg; codecs=opus","x":224,"y":167,"wires":[["600f2463.1b3f5c"]]},{"id":"e2c2df25.ef73c8","type":"inject","z":"4417bb2c.9f49e4","name":"","topic":"","payload":"Hello, my name is Watson","payloadType":"str","repeat":"","crontab":"","once":false,"x":121,"y":89.5,"wires":[["1df9a2f0.a8b265"]]},{"id":"600f2463.1b3f5c","type":"function","z":"4417bb2c.9f49e4","name":"","func":"msg.payload = msg.speech;\nreturn msg;","outputs":1,"noerr":0,"x":382,"y":171,"wires":[["e08d80ef.eaf04"]]},{"id":"e08d80ef.eaf04","type":"play audio","z":"4417bb2c.9f49e4","name":"","x":548,"y":169,"wires":[]}]

I've tried all of WAV, OGC and FLAC outputs. But it doesn't seem to work.

**Comment by lorentzlasson** [comment]
Thanks for pointing it out! It seems the output from the text to speech node had changed. I have published a new version, please try it out. The format needs to be WAV (only change needed to your flow).

**Comment by kevinxbrown** [comment]
That's great, thank you! npm is still saying version 1.0.0 and updated 7 months ago though?
http://flows.nodered.org/node/node-red-contrib-play-audio

**Comment by lorentzlasson** [comment]
The node-red view of the node is not updated yet, not sure how that is supposed to work. It is updated on npm however (v 2.0.1) and should be available to install: https://npmjs.org/package/node-red-contrib-play-audio

**Comment by kevinxbrown** [comment]
Many thanks - I've now updated packages.json to 2.x rather than 1.x, and it deploys fine - and works wonderfully!! Many thanks for your help!
