### ISSUE TITLE
Preventing sleep on firefox

### ISSUE THREAD

**Issue by gekkie** [lorentzlasson/node-red-contrib-play-audio#13]
Hi,

I just spent most of the day trying to figure out what was happening. Long story short, this plugin somehow enables the Prevent Sleep bit to be flipped on firefox 75.0 even if no flows are using the plugin what so ever. This causes my laptop to not go into sleep mode when the lid is closed and drain the battery.

Tested using a fresh build of node-red 1.0.6, no flows imported what so ever just added this plugin and it shows up immediately.

Node-red 1.0.6
play-audio 2.4.0
firefox 75.0
osx catalina 10.15.4

**Comment by dceejay** [comment]
ref discussion - https://discourse.nodered.org/t/node-red-webpage-enables-prevent-sleep-in-osx-firefox/25796

**Comment by dceejay** [comment]
It's your lucky Friday... - found the magic...

published as v2.5.0
