### ISSUE TITLE
[Question] Can we use this in background? 

### ISSUE THREAD

**Issue by henjoe** [lorentzlasson/node-red-contrib-play-audio#16]
I wanna play sound without opening the nodered admin UI, upon testing, it does not play sound when the UI admin is close. 
Is there any we can do? Thanks!

**Comment by dceejay** [comment]
As the node says - this is for use in the browser only - so yes it needs the UI running... If you want to play sounds natively on the server then you need something like [node-red-contrib-play-sound](https://flows.nodered.org/node/node-red-contrib-play-sound) or [noce0red0contrib-audio](https://flows.nodered.org/node/node-red-contrib-audio)
