### ISSUE TITLE
Is there a typo in the package.json

### ISSUE THREAD

**Issue by hammoaj** [lorentzlasson/node-red-contrib-play-audio#2]
Hi,

Everywhere else in the .js and .html files, the name of the node is referred to as "play audio", but in the package.json it is "play-audio". I'm having real problems getting it to install on bluemix, and my suspicion is that this type is causing Node-RED some problems. npm installs the module fine, and it sort of appears in Node-RED but doesn't work

**Comment by hammoaj** [comment]
Just confirmed that this is the problem. Installed the node locally with a correct package.json and it works fine.

**Comment by lorentzlasson** [comment]
Hi,

I fail to recreate the issue when going through the following steps:
1. Create new instance of node-red on Bluemix using the boilerplate in the catalog
2. Download starter code
3. Add this line to `“dependencies”` in `package.son`:  `"node-red-contrib-play-audio":"2.x”`
4. Push the code back to Bluemix using `cf push APP_NAME`

Do you do anything differently?
