### ISSUE TITLE
TTS voice initialisation

### ISSUE THREAD

**Issue by Hugobox** [lorentzlasson/node-red-contrib-play-audio#7]
Hi!
I had an issue with voice initialisation: on startup it would play a different voice than the one that was selected. But if I press on the stop button, then the next time the tts voice is used, the voice would be the one actually selected in the dropdown. So I naively modified the html file to inject the stop function during the initalisation and it works. Might not be the most elegant solution but it works for me. Let me know if you want a PR. 
Thanks!

**Comment by dceejay** [comment]
sure, let's have a look.

**Comment by Hugobox** [comment]
Nevermind! found out that my "initialisation" problem was actually that Electron uses Chromium which doesn't feature any TTS voices (aside from the native OS one). I was then opening the NR editor in Google Chrome and the voices would then reappear after a deploy.
